# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_v6.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(700, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 500))
        MainWindow.setMaximumSize(QtCore.QSize(900, 643))
        MainWindow.setSizeIncrement(QtCore.QSize(0, 0))
        MainWindow.setBaseSize(QtCore.QSize(0, 0))
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Icons/w.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(5, 67, 0, 255), stop:1 rgba(37, 190, 143, 255));\n"
"border-radius: 12px;")
        MainWindow.setInputMethodHints(QtCore.Qt.ImhNone)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(700, 500))
        self.centralwidget.setMaximumSize(QtCore.QSize(900, 643))
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setBaseSize(QtCore.QSize(0, 0))
        self.centralwidget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(5, 67, 0, 255), stop:1 rgba(37, 190, 143, 255));\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.header = QtWidgets.QWidget(self.centralwidget)
        self.header.setStyleSheet("background:transparent;\n"
"color: rgb(255, 255, 255);")
        self.header.setObjectName("header")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.header)
        self.horizontalLayout_4.setContentsMargins(9, 0, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.logo = QtWidgets.QFrame(self.header)
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.logo)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.logo_Label = QtWidgets.QLabel(self.logo)
        self.logo_Label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.logo_Label.setText("")
        self.logo_Label.setPixmap(QtGui.QPixmap("Icons/app_icon.png"))
        self.logo_Label.setObjectName("logo_Label")
        self.horizontalLayout_3.addWidget(self.logo_Label)
        self.horizontalLayout_4.addWidget(self.logo)
        self.head = QtWidgets.QFrame(self.header)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.head.sizePolicy().hasHeightForWidth())
        self.head.setSizePolicy(sizePolicy)
        self.head.setMinimumSize(QtCore.QSize(0, 0))
        self.head.setMaximumSize(QtCore.QSize(586, 16))
        self.head.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.head.setFrameShadow(QtWidgets.QFrame.Raised)
        self.head.setObjectName("head")
        self.horizontalLayout_4.addWidget(self.head)
        self.app_button = QtWidgets.QFrame(self.header)
        self.app_button.setStyleSheet("")
        self.app_button.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app_button.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_button.setObjectName("app_button")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.app_button)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimize_Button = QtWidgets.QPushButton(self.app_button)
        self.minimize_Button.setStyleSheet("")
        self.minimize_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Icons/minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimize_Button.setIcon(icon1)
        self.minimize_Button.setObjectName("minimize_Button")
        self.horizontalLayout_2.addWidget(self.minimize_Button)
        self.close_Button = QtWidgets.QPushButton(self.app_button)
        self.close_Button.setStyleSheet("")
        self.close_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Icons/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_Button.setIcon(icon2)
        self.close_Button.setObjectName("close_Button")
        self.horizontalLayout_2.addWidget(self.close_Button)
        self.horizontalLayout_4.addWidget(self.app_button, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addWidget(self.header)
        self.durum_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.durum_frame.sizePolicy().hasHeightForWidth())
        self.durum_frame.setSizePolicy(sizePolicy)
        self.durum_frame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.durum_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.durum_frame.setStyleSheet("background: red;")
        self.durum_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.durum_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.durum_frame.setObjectName("durum_frame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.durum_frame)
        self.horizontalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_10.setContentsMargins(10, 6, 10, 6)
        self.horizontalLayout_10.setSpacing(4)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.durum_Label = QtWidgets.QLabel(self.durum_frame)
        self.durum_Label.setStyleSheet("background: transparent;\n"
"color: white;\n"
"font: bold 10px;")
        self.durum_Label.setObjectName("durum_Label")
        self.horizontalLayout_10.addWidget(self.durum_Label)
        self.verticalLayout_9.addWidget(self.durum_frame)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("background:transparent;")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_5 = QtWidgets.QFrame(self.widget_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_4.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mesaj = QtWidgets.QTextEdit(self.frame_5)
        self.mesaj.setStyleSheet("background-color: #F2F2F2;\n"
"border-radius: 8px;\n"
"border-style:outset;\n"
"border-width: 2px;\n"
"font: bold 12px;")
        self.mesaj.setObjectName("mesaj")
        self.verticalLayout_4.addWidget(self.mesaj)
        self.horizontalLayout_9.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.widget_2)
        self.frame_6.setStyleSheet("background: transparent;\n"
"color: white;\n"
"font: bold 12px;")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_5.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.web_Checkbox = QtWidgets.QCheckBox(self.frame_6)
        self.web_Checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.web_Checkbox.setObjectName("web_Checkbox")
        self.verticalLayout_5.addWidget(self.web_Checkbox, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.app_Checkbox = QtWidgets.QCheckBox(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.app_Checkbox.sizePolicy().hasHeightForWidth())
        self.app_Checkbox.setSizePolicy(sizePolicy)
        self.app_Checkbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.app_Checkbox.setAutoFillBackground(False)
        self.app_Checkbox.setObjectName("app_Checkbox")
        self.verticalLayout_5.addWidget(self.app_Checkbox, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        spacerItem = QtWidgets.QSpacerItem(20, 140, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.tarih_Label = QtWidgets.QLabel(self.frame_6)
        self.tarih_Label.setObjectName("tarih_Label")
        self.verticalLayout_5.addWidget(self.tarih_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.saat_Label = QtWidgets.QLabel(self.frame_6)
        self.saat_Label.setObjectName("saat_Label")
        self.verticalLayout_5.addWidget(self.saat_Label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignBottom)
        self.horizontalLayout_9.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.widget_2)
        self.frame_7.setStyleSheet("background: transparent;\n"
"color: white;\n"
"font: bold 12px;")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.frame_7)
        self.dateTimeEdit.setStyleSheet("background-color: white;\n"
"color: black;")
        self.dateTimeEdit.setDateTime(QtCore.QDateTime(QtCore.QDate(2023, 7, 28), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setDate(QtCore.QDate(2023, 7, 28))
        self.dateTimeEdit.setMaximumDateTime(QtCore.QDateTime(QtCore.QDate(9999, 12, 31), QtCore.QTime(23, 59, 59)))
        self.dateTimeEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2023, 7, 28), QtCore.QTime(0, 0, 0)))
        self.dateTimeEdit.setMinimumDate(QtCore.QDate(2023, 7, 28))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.verticalLayout_6.addWidget(self.dateTimeEdit)
        self.zaman_Checkbox = QtWidgets.QCheckBox(self.frame_7)
        self.zaman_Checkbox.setObjectName("zaman_Checkbox")
        self.verticalLayout_6.addWidget(self.zaman_Checkbox, 0, QtCore.Qt.AlignTop)
        self.rehber_Checkbox = QtWidgets.QCheckBox(self.frame_7)
        self.rehber_Checkbox.setObjectName("rehber_Checkbox")
        self.verticalLayout_6.addWidget(self.rehber_Checkbox, 0, QtCore.Qt.AlignTop)
        self.grup_Checkbox = QtWidgets.QCheckBox(self.frame_7)
        self.grup_Checkbox.setObjectName("grup_Checkbox")
        self.verticalLayout_6.addWidget(self.grup_Checkbox, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_9.addWidget(self.frame_7, 0, QtCore.Qt.AlignTop)
        self.frame_8 = QtWidgets.QFrame(self.widget_2)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.send_Button = QtWidgets.QPushButton(self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_Button.sizePolicy().hasHeightForWidth())
        self.send_Button.setSizePolicy(sizePolicy)
        self.send_Button.setMinimumSize(QtCore.QSize(88, 100))
        self.send_Button.setMaximumSize(QtCore.QSize(100, 100))
        self.send_Button.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 85, 0);\n"
"min-width: 7em;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 8px;\n"
"font: bold 10px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: lightgreen;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #002e00;\n"
"}")
        self.send_Button.setObjectName("send_Button")
        self.verticalLayout_7.addWidget(self.send_Button)
        self.horizontalLayout_9.addWidget(self.frame_8)
        self.verticalLayout_9.addWidget(self.widget_2)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 250))
        self.widget.setStyleSheet("background:transparent;")
        self.widget.setObjectName("widget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_Rehber = QtWidgets.QFrame(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_Rehber.sizePolicy().hasHeightForWidth())
        self.frame_Rehber.setSizePolicy(sizePolicy)
        self.frame_Rehber.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Rehber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Rehber.setObjectName("frame_Rehber")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_Rehber)
        self.verticalLayout_2.setContentsMargins(9, -1, -1, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_9 = QtWidgets.QFrame(self.frame_Rehber)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_9.sizePolicy().hasHeightForWidth())
        self.frame_9.setSizePolicy(sizePolicy)
        self.frame_9.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(72, 186, 255, 255), stop:1 rgba(53, 68, 101, 255));\n"
"border-radius: 8px;")
        self.frame_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.rehbergrupliste_Label = QtWidgets.QLabel(self.frame_9)
        self.rehbergrupliste_Label.setStyleSheet("background-color: transparent;\n"
"color: white;\n"
"font: bold 12px;")
        self.rehbergrupliste_Label.setText("")
        self.rehbergrupliste_Label.setAlignment(QtCore.Qt.AlignCenter)
        self.rehbergrupliste_Label.setObjectName("rehbergrupliste_Label")
        self.verticalLayout_8.addWidget(self.rehbergrupliste_Label)
        self.table = QtWidgets.QTableWidget(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table.sizePolicy().hasHeightForWidth())
        self.table.setSizePolicy(sizePolicy)
        self.table.setMinimumSize(QtCore.QSize(0, 140))
        self.table.setStyleSheet("background: transparent;")
        self.table.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.table.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.table.setLineWidth(1)
        self.table.setMidLineWidth(0)
        self.table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.table.setAutoScroll(True)
        self.table.setAutoScrollMargin(16)
        self.table.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.table.setShowGrid(True)
        self.table.setGridStyle(QtCore.Qt.DashLine)
        self.table.setWordWrap(True)
        self.table.setCornerButtonEnabled(True)
        self.table.setRowCount(4)
        self.table.setColumnCount(3)
        self.table.setObjectName("table")
        self.table.horizontalHeader().setVisible(False)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.horizontalHeader().setDefaultSectionSize(100)
        self.table.horizontalHeader().setHighlightSections(True)
        self.table.horizontalHeader().setSortIndicatorShown(False)
        self.table.horizontalHeader().setStretchLastSection(True)
        self.table.verticalHeader().setVisible(False)
        self.table.verticalHeader().setCascadingSectionResizes(False)
        self.table.verticalHeader().setDefaultSectionSize(30)
        self.table.verticalHeader().setSortIndicatorShown(False)
        self.table.verticalHeader().setStretchLastSection(True)
        self.verticalLayout_8.addWidget(self.table)
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_10.sizePolicy().hasHeightForWidth())
        self.frame_10.setSizePolicy(sizePolicy)
        self.frame_10.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_10.setSizeIncrement(QtCore.QSize(0, 0))
        self.frame_10.setBaseSize(QtCore.QSize(0, 0))
        self.frame_10.setStyleSheet("background-color: transparent;\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_6.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_6.setSpacing(50)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.db_rehber_LoadButton = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_rehber_LoadButton.sizePolicy().hasHeightForWidth())
        self.db_rehber_LoadButton.setSizePolicy(sizePolicy)
        self.db_rehber_LoadButton.setMinimumSize(QtCore.QSize(100, 28))
        self.db_rehber_LoadButton.setStyleSheet("QPushButton {\n"
"color: #FFFFFF;\n"
"min-height: 2em;\n"
"background-color: #0F2C49;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: lightblue;\n"
"font: bold 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #669ACE;}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #071624;\n"
"}")
        self.db_rehber_LoadButton.setAutoDefault(False)
        self.db_rehber_LoadButton.setObjectName("db_rehber_LoadButton")
        self.horizontalLayout_6.addWidget(self.db_rehber_LoadButton)
        self.db_grup_LoadButton = QtWidgets.QPushButton(self.frame_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.db_grup_LoadButton.sizePolicy().hasHeightForWidth())
        self.db_grup_LoadButton.setSizePolicy(sizePolicy)
        self.db_grup_LoadButton.setMinimumSize(QtCore.QSize(100, 28))
        self.db_grup_LoadButton.setStyleSheet("QPushButton {\n"
"color: #FFFFFF;\n"
"min-height: 2em;\n"
"background-color: #0F2C49;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 6px;\n"
"border-color: lightblue;\n"
"font: bold 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #669ACE;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #071624;\n"
"}")
        self.db_grup_LoadButton.setObjectName("db_grup_LoadButton")
        self.horizontalLayout_6.addWidget(self.db_grup_LoadButton)
        self.verticalLayout_8.addWidget(self.frame_10)
        self.verticalLayout_2.addWidget(self.frame_9)
        self.horizontalLayout_5.addWidget(self.frame_Rehber)
        self.frame_2 = QtWidgets.QFrame(self.widget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_3.setSpacing(9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 120))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_4.setStyleSheet("background-color: rgb(0, 170, 0);\n"
"color: white;\n"
"font: bold 12px;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(-1, 9, -1, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.yeniKayit_Label = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yeniKayit_Label.sizePolicy().hasHeightForWidth())
        self.yeniKayit_Label.setSizePolicy(sizePolicy)
        self.yeniKayit_Label.setMinimumSize(QtCore.QSize(0, 0))
        self.yeniKayit_Label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.yeniKayit_Label.setObjectName("yeniKayit_Label")
        self.verticalLayout.addWidget(self.yeniKayit_Label, 0, QtCore.Qt.AlignHCenter)
        self.yeniKayit_Name_lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.yeniKayit_Name_lineEdit.setStyleSheet("color:white;\n"
"background-color: rgba(0,0,0,0);\n"
"border:none;\\n\n"
"border-radius: 0px;\n"
"border-bottom:1.5px solid lightgreen;\n"
"padding-bottom:7px;")
        self.yeniKayit_Name_lineEdit.setMaxLength(100)
        self.yeniKayit_Name_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.yeniKayit_Name_lineEdit.setObjectName("yeniKayit_Name_lineEdit")
        self.verticalLayout.addWidget(self.yeniKayit_Name_lineEdit)
        self.yeniKayit_Surname_lineEdit = QtWidgets.QLineEdit(self.frame_4)
        self.yeniKayit_Surname_lineEdit.setStyleSheet("color:white;\n"
"background-color: rgba(0,0,0,0);\n"
"border:none;\\n\n"
"border-radius: 0px;\n"
"border-bottom:1.5px solid lightgreen;\n"
"padding-bottom:7px;")
        self.yeniKayit_Surname_lineEdit.setMaxLength(100)
        self.yeniKayit_Surname_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.yeniKayit_Surname_lineEdit.setObjectName("yeniKayit_Surname_lineEdit")
        self.verticalLayout.addWidget(self.yeniKayit_Surname_lineEdit)
        self.yeniKayit_Button = QtWidgets.QPushButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.yeniKayit_Button.sizePolicy().hasHeightForWidth())
        self.yeniKayit_Button.setSizePolicy(sizePolicy)
        self.yeniKayit_Button.setMinimumSize(QtCore.QSize(0, 0))
        self.yeniKayit_Button.setStyleSheet("QPushButton {\n"
"background-color: rgb(0, 85, 0);\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 8px;\n"
"font: bold 10px;\n"
"max-height: 2em;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: lightgreen;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #002e00;\n"
"}")
        self.yeniKayit_Button.setObjectName("yeniKayit_Button")
        self.verticalLayout.addWidget(self.yeniKayit_Button)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:0, y2:0, stop:0 rgba(44, 0, 67, 255), stop:1 rgba(137, 37, 190, 255));")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_7.setContentsMargins(-1, 9, -1, 9)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.grup_name = QtWidgets.QLabel(self.frame_3)
        self.grup_name.setStyleSheet("background: transparent;\n"
"color: white;\n"
"font: bold 12px;")
        self.grup_name.setObjectName("grup_name")
        self.horizontalLayout_7.addWidget(self.grup_name)
        self.grup_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.grup_lineEdit.setStyleSheet("color: white;\n"
"background-color: #CA8CE7;\n"
"border-radius: 8px;\n"
"font: bold 12px;")
        self.grup_lineEdit.setText("")
        self.grup_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.grup_lineEdit.setObjectName("grup_lineEdit")
        self.horizontalLayout_7.addWidget(self.grup_lineEdit)
        self.grupEkle_Button = QtWidgets.QPushButton(self.frame_3)
        self.grupEkle_Button.setStyleSheet("QPushButton{\n"
"background-color: #AF125E;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 8px;\n"
"border-color:lightpink;\n"
"font: bold 10px;\n"
"min-width: 4em;\n"
"padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #FFA2CF\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #8a0e4a;\n"
"}")
        self.grupEkle_Button.setObjectName("grupEkle_Button")
        self.horizontalLayout_7.addWidget(self.grupEkle_Button)
        self.grupSil_Button = QtWidgets.QPushButton(self.frame_3)
        self.grupSil_Button.setStyleSheet("QPushButton{\n"
"background-color: #AF125E;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 8px;\n"
"border-color:lightpink;\n"
"font: bold 10px;\n"
"min-width: 4em;\n"
"padding: 6px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #FFA2CF\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"background-color: #8a0e4a;\n"
"}")
        self.grupSil_Button.setObjectName("grupSil_Button")
        self.horizontalLayout_7.addWidget(self.grupSil_Button)
        self.verticalLayout_3.addWidget(self.frame_3, 0, QtCore.Qt.AlignBottom)
        self.frame = QtWidgets.QFrame(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setStyleSheet("background-color: rgb(53, 68, 101);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_8.setContentsMargins(-1, 9, -1, 9)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rehber_name = QtWidgets.QLabel(self.frame)
        self.rehber_name.setStyleSheet("background: transparent;\n"
"color: white;\n"
"font: bold 12px;")
        self.rehber_name.setObjectName("rehber_name")
        self.horizontalLayout_8.addWidget(self.rehber_name)
        self.rehber_lineEdit = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rehber_lineEdit.sizePolicy().hasHeightForWidth())
        self.rehber_lineEdit.setSizePolicy(sizePolicy)
        self.rehber_lineEdit.setStyleSheet("color: white;\n"
"background-color: rgb(88, 114, 168);\n"
"border-radius: 8px;\n"
"font: bold 12px;")
        self.rehber_lineEdit.setInputMask("")
        self.rehber_lineEdit.setText("")
        self.rehber_lineEdit.setMaxLength(32767)
        self.rehber_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.rehber_lineEdit.setObjectName("rehber_lineEdit")
        self.horizontalLayout_8.addWidget(self.rehber_lineEdit)
        self.rehber_delete = QtWidgets.QPushButton(self.frame)
        self.rehber_delete.setStyleSheet("QPushButton {\n"
"background-color: #0F2C49;\n"
"color: #FFFFFF;\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 8px;\n"
"border-color:lightblue;\n"
"font: bold 10px;\n"
"min-width: 4em;\n"
"padding: 6px;\n"
"}\n"
"QPushButton:hover {\n"
"background-color: #669ACE;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color: #071624;\n"
"}")
        self.rehber_delete.setObjectName("rehber_delete")
        self.horizontalLayout_8.addWidget(self.rehber_delete)
        self.verticalLayout_3.addWidget(self.frame, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.verticalLayout_9.addWidget(self.widget)
        self.footer = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.footer.sizePolicy().hasHeightForWidth())
        self.footer.setSizePolicy(sizePolicy)
        self.footer.setMinimumSize(QtCore.QSize(0, 45))
        self.footer.setStyleSheet("background:transparent;")
        self.footer.setObjectName("footer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.footer)
        self.horizontalLayout.setContentsMargins(-1, 10, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.app_name = QtWidgets.QLabel(self.footer)
        self.app_name.setStyleSheet("background: transparent;\n"
"color: lightgreen;\n"
"border-radius: 0px")
        self.app_name.setObjectName("app_name")
        self.horizontalLayout.addWidget(self.app_name)
        spacerItem1 = QtWidgets.QSpacerItem(25, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.site_Label = QtWidgets.QLabel(self.footer)
        self.site_Label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.site_Label.setStyleSheet("background: transparent;\n"
"color: lightgreen;\n"
"border-radius: 0px")
        self.site_Label.setObjectName("site_Label")
        self.horizontalLayout.addWidget(self.site_Label)
        spacerItem2 = QtWidgets.QSpacerItem(855, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.github_Label = QtWidgets.QLabel(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.github_Label.sizePolicy().hasHeightForWidth())
        self.github_Label.setSizePolicy(sizePolicy)
        self.github_Label.setMinimumSize(QtCore.QSize(32, 35))
        self.github_Label.setMaximumSize(QtCore.QSize(32, 35))
        self.github_Label.setStyleSheet("background:transparent;\n"
"border-radius:0px;")
        self.github_Label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.github_Label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.github_Label.setText("")
        self.github_Label.setPixmap(QtGui.QPixmap("Icons/github.png"))
        self.github_Label.setScaledContents(False)
        self.github_Label.setObjectName("github_Label")
        self.horizontalLayout.addWidget(self.github_Label)
        self.size_frame = QtWidgets.QFrame(self.footer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.size_frame.sizePolicy().hasHeightForWidth())
        self.size_frame.setSizePolicy(sizePolicy)
        self.size_frame.setMinimumSize(QtCore.QSize(8, 8))
        self.size_frame.setMaximumSize(QtCore.QSize(8, 8))
        self.size_frame.setSizeIncrement(QtCore.QSize(8, 8))
        self.size_frame.setBaseSize(QtCore.QSize(8, 8))
        self.size_frame.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.size_frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.size_frame.setStyleSheet("")
        self.size_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.size_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.size_frame.setLineWidth(1)
        self.size_frame.setMidLineWidth(0)
        self.size_frame.setObjectName("size_frame")
        self.label = QtWidgets.QLabel(self.size_frame)
        self.label.setGeometry(QtCore.QRect(0, 0, 8, 8))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(8, 8))
        self.label.setMaximumSize(QtCore.QSize(8, 8))
        self.label.setSizeIncrement(QtCore.QSize(8, 8))
        self.label.setBaseSize(QtCore.QSize(8, 8))
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Icons/resize_ikon.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.size_frame, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout_9.addWidget(self.footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.durum_Label.setText(_translate("MainWindow", "DURUM: "))
        self.mesaj.setPlaceholderText(_translate("MainWindow", "MESAJINIZI YAZINIZ..."))
        self.web_Checkbox.setText(_translate("MainWindow", "WEB"))
        self.app_Checkbox.setText(_translate("MainWindow", "Uygulama"))
        self.tarih_Label.setText(_translate("MainWindow", "00.00.0000"))
        self.saat_Label.setText(_translate("MainWindow", "00:00:00"))
        self.zaman_Checkbox.setText(_translate("MainWindow", "Zamanlı"))
        self.rehber_Checkbox.setText(_translate("MainWindow", "Rehber"))
        self.grup_Checkbox.setText(_translate("MainWindow", "Grup"))
        self.send_Button.setText(_translate("MainWindow", "GÖNDER"))
        self.table.setSortingEnabled(False)
        self.db_rehber_LoadButton.setText(_translate("MainWindow", "REHBERİ YÜKLE"))
        self.db_grup_LoadButton.setText(_translate("MainWindow", "GRUBU YÜKLE"))
        self.yeniKayit_Label.setText(_translate("MainWindow", "YENİ KAYIT"))
        self.yeniKayit_Name_lineEdit.setPlaceholderText(_translate("MainWindow", "İsim - Soyisim"))
        self.yeniKayit_Surname_lineEdit.setPlaceholderText(_translate("MainWindow", "Numara"))
        self.yeniKayit_Button.setText(_translate("MainWindow", "KAYDET"))
        self.grup_name.setText(_translate("MainWindow", "GRUP"))
        self.grup_lineEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.grupEkle_Button.setText(_translate("MainWindow", "EKLE"))
        self.grupSil_Button.setText(_translate("MainWindow", "SİL"))
        self.rehber_name.setText(_translate("MainWindow", "REHBER"))
        self.rehber_lineEdit.setPlaceholderText(_translate("MainWindow", "0"))
        self.rehber_delete.setText(_translate("MainWindow", "SİL"))
        self.app_name.setText(_translate("MainWindow", "Whatsapp Mesaj Gönderici v1.1"))
        self.site_Label.setText(_translate("MainWindow", "alpayozturk.net"))
